services:
  sim:
    image: test
    container_name: pds-sim
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/tmp/.docker.xauth}:/tmp/.docker.xauth
      - .:/root/ardu_ws/src/ardupilot_gz
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: true
    tty: true
    working_dir: /root/ardu_ws/src/ardupilot_gz/launch
    command: >
      /bin/bash -c "
      cd /root/ardu_ws &&
      colcon build --packages-up-to ardupilot_gz_bringup &&
      echo 'source /root/ardu_ws/install/setup.bash' >> ~/.bashrc &&
      tail -f /dev/null
      "

  sim-gpu:
    image: ardupilot-sitl-gazebo:gpu
    container_name: pds-sim-gpu
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - ../Sistemas:/root/Sistemas
      - ../Chorus:/root/Chorus
      - ../MAVKit:/root/MAVKit
      - ../RoboChart2Python-PDS:/root/RoboChart2Python-PDS
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/tmp/.docker.xauth}:/tmp/.docker.xauth
      - .:/root/ardu_ws/src/ardupilot_gz
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=all
    stdin_open: true
    tty: true
    working_dir: /root/ardu_ws/src/ardupilot_gz/launch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      /bin/bash -c "
      cd /root/ardu_ws &&
      colcon build --packages-up-to ardupilot_gz_bringup &&
      echo 'source /root/ardu_ws/install/setup.bash' >> ~/.bashrc &&
      tail -f /dev/null
      "